### ISSUE TITLE
카페 분류! 

### ISSUE THREAD

**Issue by gudwl** [2021-SMHRD-KDT-AI-7/CafePlease#34]
- [x] 광산구 @leeminsu87 
- [x] 남구 @PaKKyU 
- [x] 동구 @gudwl 
- [x] 서구 @KKangKK 
- [x] 북구 @minsol16

**Comment by leeminsu87** [comment]
동구
1.데이오프나이트 
2.오드블랙 
3.카페미술관 
4.웨어하우스 
5.올데이피크닉

북구
1. 북구카페얼씨
2. 북구카페목화당
3. 북구 라본카페
4. 북구가배당
5. 북구구르미머무는

서구
1.상무지구 카페304 
2.서구 노브펩 
3.온클라우드나인 상무점 
4.서구 도지커피 
5.서구 가배당
